"""add_last_email_sent_to_notification_log

Revision ID: 8bc7dcdedfde
Revises: d9a59ab37bf2
Create Date: 2025-08-17 20:20:30.133284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bc7dcdedfde'
down_revision: Union[str, None] = 'd9a59ab37bf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_email_notification_log', sa.Column('last_email_sent', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_email_notification_log', 'last_email_sent')
    # ### end Alembic commands ###
