"""add winning_outcome to user_arbitrages

Revision ID: 9661e6e53d43
Revises: 989170bd98e4
Create Date: 2025-05-20 12:52:14.699111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9661e6e53d43'
down_revision: Union[str, None] = '989170bd98e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_arbitrages', sa.Column('winning_outcome', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_arbitrages', 'winning_outcome')
    # ### end Alembic commands ###
