"""add bet_amount and profit to user_arbitrages

Revision ID: 989170bd98e4
Revises: 
Create Date: 2025-05-20 12:40:24.174224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '989170bd98e4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if table exists before dropping indexes and table
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    
    if 'odds' in inspector.get_table_names():
        # Only drop indexes and table if they exist
        try:
            op.drop_index('ix_odds_away_team', table_name='odds', if_exists=True)
        except:
            pass
        try:
            op.drop_index('ix_odds_commence_time', table_name='odds', if_exists=True)
        except:
            pass
        try:
            op.drop_index('ix_odds_home_team', table_name='odds', if_exists=True)
        except:
            pass
        try:
            op.drop_index('ix_odds_id', table_name='odds', if_exists=True)
        except:
            pass
        try:
            op.drop_index('ix_odds_sport_key', table_name='odds', if_exists=True)
        except:
            pass
        try:
            op.drop_index('ix_odds_sportsbook', table_name='odds', if_exists=True)
        except:
            pass
        try:
            op.drop_table('odds')
        except:
            pass
    
    # Check if columns already exist before adding them
    existing_columns = [col['name'] for col in inspector.get_columns('user_arbitrages')]
    if 'bet_amount' not in existing_columns:
        op.add_column('user_arbitrages', sa.Column('bet_amount', sa.Float(), nullable=True))
    if 'profit' not in existing_columns:
        op.add_column('user_arbitrages', sa.Column('profit', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_arbitrages', 'profit')
    op.drop_column('user_arbitrages', 'bet_amount')
    op.create_table('odds',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sportsbook', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sport_key', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sport_title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('home_team', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('away_team', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('commence_time', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('outcome', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('odds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='odds_pkey')
    )
    op.create_index('ix_odds_sportsbook', 'odds', ['sportsbook'], unique=False)
    op.create_index('ix_odds_sport_key', 'odds', ['sport_key'], unique=False)
    op.create_index('ix_odds_id', 'odds', ['id'], unique=False)
    op.create_index('ix_odds_home_team', 'odds', ['home_team'], unique=False)
    op.create_index('ix_odds_commence_time', 'odds', ['commence_time'], unique=False)
    op.create_index('ix_odds_away_team', 'odds', ['away_team'], unique=False)
    # ### end Alembic commands ###
